#############################
###      argocd-apps      ###
#############################

cluster:
  name: nonprd
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    targetRevision: main
