#############################
###      argocd-apps      ###
#############################

cluster:
  name: prd
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    targetRevision: main
apps:
  argocd-server:
    enabled: true
  application-2:
    namespace: application-2
    enabled: true
