{{- if index .Values.apps "application-1" "enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ (printf "%s-%s" .Values.cluster.name "application-1" ) | trimPrefix "-" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  namespace: default
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  labels:
  {{- include "argocd-apps.labels" . | nindent 4 }}
spec:
  destination:
    namespace: {{ (printf "%s-%s" .Values.cluster.name "application-1" ) | trimPrefix "-" }}
    server: {{ .Values.cluster.destination.server }}
  project: {{ .Values.cluster.project }}
  source:
    path: {{ .Values.cluster.source.basePath }}application-1
    repoURL: {{ .Values.cluster.source.repoURL }}
    targetRevision: {{ .Values.cluster.source.targetRevision }}
    helm:
      valueFiles:
        - ../values.{{ .Values.cluster.name }}.yaml
  {{- if index .Values.apps "application-1" "sync" }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
  {{- end }}
{{- end }}
