{{- if index .Values.apps "argocd-server" "enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ (printf "%s-%s" .Values.cluster.name "argocd-server" ) | trimPrefix "-" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  namespace: default
  labels:
  {{- include "argocd-apps.labels" . | nindent 4 }}
spec:
  destination:
    namespace: {{ .Values.cluster.destination.namespace }}
    server: {{ .Values.cluster.destination.server }}
  project: {{ .Values.cluster.project }}
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo/argo-cd
    helm:
      releaseName: argo-cd
    targetRevision: 3.28.0
  {{- if index .Values.apps "argocd-server" "sync" }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
  {{- end }}
{{- end }}
