{{- if index .Values.apps "argocd-apps" "enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ (printf "%s-%s" .Values.cluster.name "argocd-apps" ) | trimPrefix "-" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  namespace: default
  labels:
  {{- include "argocd-apps.labels" . | nindent 4 }}
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: {{ .Values.cluster.project }}
  source:
    path: {{ .Values.cluster.source.basePath }}argocd-apps
    repoURL: {{ .Values.cluster.source.repoURL }}
    targetRevision: {{ .Values.cluster.source.targetRevision }}
    helm:
      valueFiles:
        - values.yaml
        - ../values.{{ .Values.cluster.name }}.yaml
  {{- if index .Values.apps "argocd-apps" "sync" }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
  {{- end }}
{{- end }}
