cluster:
  name: ''
  project: default
  source:
    targetRevision: main
    basePath: ./
    repoURL: https://github.com/AndriiOmelianenko/argocd-demo.git
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
apps:
  argocd-apps:
    enabled: false
    sync: true
  argocd-server:
    enabled: false
    sync: false
  application-1:
    namespace: application-1
    enabled: true
    sync: false
  application-2:
    namespace: application-2
    enabled: false
    sync: false
